### ISSUE TITLE
Add config flag for disableHardwareAcceleration?

### ISSUE THREAD

**Issue by scotthansonde** [scripting/electronLand#3]
I'm building a project for the Linux environment on Chromebook with Electron 7.1.10 (Chromium version 78). Linux on the Chromebook is a virtual environment, and this version of Chromium has a bug where hardware acceleration is unstable in a virtual environment and makes my app unusable.

Ultimately I should upgrade my project to the current version of Electron, but in the meantime I can make my app work by disabling hardware acceleration at [line 666 of lib/electronmain.js](https://github.com/scripting/electronLand/blob/master/lib/electronmain.js#L666) just before `electron.app.on` is called:

```
	...
	if (config.flPreventAppSuspension) {
		electron.powerSaveBlocker.start ("prevent-app-suspension");
	}
→	electron.app.disableHardwareAcceleration();
	electron.app.on ("ready", function () { 
	...
```

It'd be nice if there were a config flag to set this. 😃

**Comment by scripting** [comment]
@scotthansonde -- I have made the addition of config.flPreventHardwareAcceleration.

Hope this helps. :smile:

**Comment by scotthansonde** [comment]
Tested and it works as expected. 👍
